const express = require("express")
const router = express.Router()
const { authenticate } = require('../auth/auth')
const { get, create, update, leave, add, remove, call, webhook , callJoined, callLeft} = require("./channel")
router.route("/get").get(authenticate, get)
router.route("/create").post(authenticate, create)
router.route("/update").post(authenticate, update)
router.route("/leave").post(authenticate, leave)
router.route("/add").post(authenticate, add)
router.route("/remove").post(authenticate, add)
router.route("/call").post(authenticate, call)
router.route("/webhook/callJoined").post(webhook.callJoined)
router.route("/webhook/callLeft").post(webhook.callLeft)
// router.route("/calljoined").post(callJoined)
// router.route("/callleft").post(callLeft)

module.exports = router     